#!/usr/bin/env bash

set -x

#appid="application_1563963336862_0005"
#shift

if [ $# -gt 0 ]; then
  applog="$1"
else
  echo Usage: yarn-container-logs <applicationId>.log
  exit -1
fi

appid=$(basename -s ".log" "$applog")
inputlogfile="$PWD/${appid}.log"
dest_dir="$PWD/$appid"
mkdir -p "$dest_dir"
cd "$dest_dir"

containers_dir="$dest_dir/containers"
mkdir -p "$containers_dir"
cd "$containers_dir"

logfile="$dest_dir/logs"
cp "$inputlogfile" "$logfile"

if [ -s "$logfile" ]; then
  echo "Found existing logs file at $logfile; splitting per-container..."
  split-yarn-logs-per-container "$logfile"
else
  echo "Please download logs for $appid first"
  exit -1
fi

cd "$dest_dir"
echo "Done splitting; rename and create per-host directories..."
rename-and-link-hosts

echo "Look for driver containers and application masters..."
link-driver-logs
link-app-masters

echo "Creating EID symlinks..."
link-eids

